/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualisationIndexRouteImport } from './routes/visualisation/index'
import { Route as TradesIndexRouteImport } from './routes/trades/index'
import { Route as ExceptionsIndexRouteImport } from './routes/exceptions/index'
import { Route as CallbackIndexRouteImport } from './routes/callback/index'
import { Route as TradesTradeIdRouteImport } from './routes/trades/$tradeId'
import { Route as ExceptionsExceptionIdRouteImport } from './routes/exceptions/$exceptionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualisationIndexRoute = VisualisationIndexRouteImport.update({
  id: '/visualisation/',
  path: '/visualisation/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsIndexRoute = ExceptionsIndexRouteImport.update({
  id: '/exceptions/',
  path: '/exceptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackIndexRoute = CallbackIndexRouteImport.update({
  id: '/callback/',
  path: '/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesTradeIdRoute = TradesTradeIdRouteImport.update({
  id: '/trades/$tradeId',
  path: '/trades/$tradeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsExceptionIdRoute = ExceptionsExceptionIdRouteImport.update({
  id: '/exceptions/$exceptionId',
  path: '/exceptions/$exceptionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/callback': typeof CallbackIndexRoute
  '/exceptions': typeof ExceptionsIndexRoute
  '/trades': typeof TradesIndexRoute
  '/visualisation': typeof VisualisationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/callback': typeof CallbackIndexRoute
  '/exceptions': typeof ExceptionsIndexRoute
  '/trades': typeof TradesIndexRoute
  '/visualisation': typeof VisualisationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/callback/': typeof CallbackIndexRoute
  '/exceptions/': typeof ExceptionsIndexRoute
  '/trades/': typeof TradesIndexRoute
  '/visualisation/': typeof VisualisationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exceptions/$exceptionId'
    | '/trades/$tradeId'
    | '/callback'
    | '/exceptions'
    | '/trades'
    | '/visualisation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exceptions/$exceptionId'
    | '/trades/$tradeId'
    | '/callback'
    | '/exceptions'
    | '/trades'
    | '/visualisation'
  id:
    | '__root__'
    | '/'
    | '/exceptions/$exceptionId'
    | '/trades/$tradeId'
    | '/callback/'
    | '/exceptions/'
    | '/trades/'
    | '/visualisation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExceptionsExceptionIdRoute: typeof ExceptionsExceptionIdRoute
  TradesTradeIdRoute: typeof TradesTradeIdRoute
  CallbackIndexRoute: typeof CallbackIndexRoute
  ExceptionsIndexRoute: typeof ExceptionsIndexRoute
  TradesIndexRoute: typeof TradesIndexRoute
  VisualisationIndexRoute: typeof VisualisationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualisation/': {
      id: '/visualisation/'
      path: '/visualisation'
      fullPath: '/visualisation'
      preLoaderRoute: typeof VisualisationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions/': {
      id: '/exceptions/'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/': {
      id: '/callback/'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$tradeId': {
      id: '/trades/$tradeId'
      path: '/trades/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof TradesTradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions/$exceptionId': {
      id: '/exceptions/$exceptionId'
      path: '/exceptions/$exceptionId'
      fullPath: '/exceptions/$exceptionId'
      preLoaderRoute: typeof ExceptionsExceptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExceptionsExceptionIdRoute: ExceptionsExceptionIdRoute,
  TradesTradeIdRoute: TradesTradeIdRoute,
  CallbackIndexRoute: CallbackIndexRoute,
  ExceptionsIndexRoute: ExceptionsIndexRoute,
  TradesIndexRoute: TradesIndexRoute,
  VisualisationIndexRoute: VisualisationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
