/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradesIndexRouteImport } from './routes/trades/index'
import { Route as ExceptionsIndexRouteImport } from './routes/exceptions/index'
import { Route as TradesTradeIdRouteImport } from './routes/trades/$tradeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesIndexRoute = TradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsIndexRoute = ExceptionsIndexRouteImport.update({
  id: '/exceptions/',
  path: '/exceptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesTradeIdRoute = TradesTradeIdRouteImport.update({
  id: '/trades/$tradeId',
  path: '/trades/$tradeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/exceptions': typeof ExceptionsIndexRoute
  '/trades': typeof TradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/exceptions': typeof ExceptionsIndexRoute
  '/trades': typeof TradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trades/$tradeId': typeof TradesTradeIdRoute
  '/exceptions/': typeof ExceptionsIndexRoute
  '/trades/': typeof TradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trades/$tradeId' | '/exceptions' | '/trades'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trades/$tradeId' | '/exceptions' | '/trades'
  id: '__root__' | '/' | '/trades/$tradeId' | '/exceptions/' | '/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TradesTradeIdRoute: typeof TradesTradeIdRoute
  ExceptionsIndexRoute: typeof ExceptionsIndexRoute
  TradesIndexRoute: typeof TradesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/': {
      id: '/trades/'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions/': {
      id: '/exceptions/'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$tradeId': {
      id: '/trades/$tradeId'
      path: '/trades/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof TradesTradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TradesTradeIdRoute: TradesTradeIdRoute,
  ExceptionsIndexRoute: ExceptionsIndexRoute,
  TradesIndexRoute: TradesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
